[package]
name = "game"
version = "0.1.0"
authors = ["Jonathan Nilsson <jonathan@voysys.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = { version = "0.7", default-features = false }
n64 = { path = "../n64" }
n64-math = { path = "../n64-math" }
zerocopy = "0.3"

[target.'cfg(target_vendor = "nintendo64")'.dependencies]
n64-alloc = { path = "../n64-alloc" }
n64-sys = { path = "../n64-sys" }

[build-dependencies]
hound = "3"
n64-math = { path = "../n64-math" }
png = { version = "0.16", default-features = false }
tiled = { git = "https://github.com/JoNil/rs-tiled.git" }
zerocopy = "0.3"
