[package]
name = "deploy"
version = "0.1.0"
authors = ["Jonathan Nilsson <jonathan@voysys.se>"]
edition = "2021"

[dependencies]
serialport = "4"
puffin = { version = "0.13", features = ["packing", "serialization"] }
puffin_http = "0.10"