[package]
name = "deploy"
version = "0.1.0"
authors = ["Jonathan Nilsson <jonathan@voysys.se>"]
edition = "2021"

[dependencies]
n64-types = { path = "../n64-types" }
puffin = { version = "0.13", features = ["packing", "serialization"] }
puffin_http = "0.10"
serialport = "4"